services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin_user
      POSTGRES_DB: symptomatologic
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data:100M
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 50M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
#    command: >
#      sh -c "python -m main.migrate migrate &&
#            python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://admin_user:password@postgres:5432/symptomatologic
      SECRET_KEY: 9f37d951ec4d12453a2218334154f4d4c2ea57becc18907c9ac9e6e013f165c8
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      - postgres
    networks:
      - app_network
    volumes:
      - ./backend_volumes:/var/lib/backend:100M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 50M

  backend_migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://admin_user:password@postgres:5432/symptomatologic
    command: [ "sh", "-c", "python -m main.migrate migrate" ]
    depends_on:
      - postgres
    networks:
      - app_network
pg_admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
networks:
  app_network:
    driver: bridge